### PR TITLE
Dockerfile and dotnet 7

### PR DESCRIPTION
**Pull request by aeb-dev**

### CODE REVIEW

**Comment by phatboyg** [comment]
I'm not updating this for .NET7, and the code itself has been merged into the main MassTransit repository.

**Comment by aeb-dev** [comment]
It is under tests, sorry did not see. Would you want me to add dockerfile there?

**Comment by phatboyg** [comment]
Why would you run it in docker? How would you pass arguments to it? Seems odd to me, why anyone would do that in a container anyway.

**Comment by aeb-dev** [comment]
Well, I have a kubernetes environment and I would like to see how it behaves.

You can connect to shell and run commands like:
`dotnet mtbench.dll --rabbitmq ...`

**Comment by aeb-dev** [comment]
Rabbitmq has its own performance test tool which also has docker image:

https://github.com/rabbitmq/rabbitmq-perf-test

**Comment by phatboyg** [comment]
Huh, fair enough. You can submit a PR on develop, but it needs to be .NET 6.

**Pull request closed without merging**
